name = "Scattensor"
uuid = "95672735-de0d-45b0-8477-63c31bb62d2b"
version = "1.0.0-DEV"
authors = ["Mattia Morgavi"]

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
ITensorMPS = "0d1a4710-d33b-49a5-8f18-73bdf49b47e2"
ITensors = "9136182c-28ba-11e9-034c-db9fb085ebd5"
KrylovKit = "0b1a1467-8014-51b9-945f-bf0ae24f4b77"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Measures = "442fdcdd-2543-5da2-b0f3-8c86c306513e"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
PGFPlotsX = "8314cec4-20b6-5062-9cdb-752b83310925"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Colors = "0.13.0"
ITensorMPS = "0.3.1"
ITensors = "0.9.14"
KrylovKit = "0.8, 0.9, 0.10"
LaTeXStrings = "1.4.0"
Logging = "1.11.0"
Measures = "0.3.2"
PGFPlotsX = "1.6.2"
Revise = "3.6.2"
SparseArrays = "1.11.0"
Test = "1.11.0"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
